# version: '3.8'

# services:
#   backend:
#     build:
#       context: ./server
#       dockerfile: Dockerfile
#     container_name: my-backend
#     ports:
#       - "7002:7002"  # לחשוף את הבקאנד ל-host
#     env_file:
#       - ./server/.env
#     depends_on:
#       - mongo
#     networks:
#       - ai-network

#   frontend:
#     build:
#       context: ./client
#       dockerfile: Dockerfile
#     container_name: my-frontend
#     ports:
#       - "5173:80"  # נגיש דרך localhost:5173
#     depends_on:
#       - backend
#     networks:
#       - ai-network

#   mongo:
#     image: mongo
#     container_name: mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db
#     networks:
#       - ai-network

# networks:
#   ai-network:

# volumes:
#   mongo_data:

version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ai-network

  backend:
    build:
      context: ./server
    container_name: my-backend
    ports:
      - "7002:7002"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - ai-network

  frontend:
    build:
      context: ./client
    container_name: my-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - ai-network

volumes:
  mongo_data:

networks:
  ai-network:
